### PR TITLE
Allow users to configure default git branch name

### PR DESCRIPTION
**Pull request by JonathanLorimer**

### CODE REVIEW

**Comment by Ericson2314** [comment]
@QAston sorry I didn't respond sooner, are you saying this fix is insufficient on its own?

**Comment by QAston** [comment]
Yes, I think so. Might be a different problem though - my cargo file pointed to the correct branch but it was ignored by cargo.nix, maybe in the OP's case there was no branch set in cargo files.

**Comment by kolloch** [comment]
Heyo @QAston / @Ericson2314,

I am doing some clean up work... I guess we can close this?

**Comment by kolloch** [comment]
(otherwise reopen)

**Comment by QAston** [comment]
no idea, I moved on from nix, I hope I never have to go back

**Pull request closed without merging**
